
export default ({
    SET_FORM_SEARCH: 'SET_FORM_SEARCH',
    SET_NEW_FIELD: 'SET_NEW_FIELD',
    SET_SEARCHES: 'SET_SEARCHES',

    SNACKBAR_HIDE: 'SNACKBAR_HIDE',
    SNACKBAR_SHOW: 'SNACKBAR_SHOW'
});
